# Builds pull requests before merge
name: Build PR

on:
  pull_request:

jobs:
  build:
    uses: xemantic/.github/.github/workflows/build-gradle.yml@main
    secrets: inherit
    with:
      gradle_args: build -PjvmOnlyBuild=false
      env: |
        ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
