# Builds main branch and deploys SNAPSHOT versions to Maven Central
name: Build main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: xemantic/.github/.github/workflows/build-gradle.yml@main
    secrets:
      inherit
    with:
      gradle_args: -PjvmOnlyBuild=false build publishToMavenCentral --no-configuration-cache
      maven_central: true
      anthropic: true
